#COLAB 설정

google drive mount  
google drive를 colab환경에 mount해서 colab에서 파일을 읽고 쓸수 있도록 설정  

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [13]:
import os
print(os.getcwd())  # !pwd
print(os.listdir()) # !ls
print(os.listdir(os.path.join("drive","MyDrive")))  # !ls drive/MyDrive

/content
['.config', 'drive', 'sample_data']
['Colab Notebooks', 'private', 'yolov5', 'labeling', 'Yolov5_StrongSORT_OSNet', 'yolov8_tracking', 'video', 'wos-core_SCIE 2023-July-17.gsheet', 'nlp-open-tutorial']


# NUMPY 실습

In [14]:
import numpy as np
import pandas as pd
import torch

Ndarray  
numpy.array()함수에 list like형태의 데이터를 입력하여 생성한다.  
doc: https://compmath.korea.ac.kr/appmath/NumpyBasics.html  

In [15]:
data = [1,2,3]
print(type(data))

numpy_data = np.array(data)
print(numpy_data)
print(type(numpy_data))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


Ndarray는 행렬 형태의 데이터   
행렬은 각 행과 열에 데이터의 크기가 같아야한다.

python의 list는 단순 데이터의 묶음 형태이기 때문에 [[1,2],1,(1,2,3)] 같이 각 element의 형태, 크기, 타입이 자유로움   
numpy의 ndarray는 행렬, 텐서와 같은형태를 가지기 때문에 각 elements의 타입이 동일해야하며 모든 열과 행의 크기가 같아야 함

In [20]:
python_list = [[1,2],1,(1.0,2,3),"string"]
print(python_list)

#ndarray는 모든 행과 열의 크기가 같아야하기에 정상적인 데이터가 생성되지 않음
a = [[1,2],[1,2,3]]
np_a = np.array(a)
print("\n")
print(np_a)
print(np_a.shape)
print(type(np_a))

#2차원 list를 이용한 ndarray 생성
b = [[1,2,3],[4,5,6]]
np_b = np.array(b)
print("\n")
print(np_b)
print(np_b.shape)
print(type(np_b))


[[1, 2], 1, (1.0, 2, 3), 'string']


[list([1, 2]) list([1, 2, 3])]
(2,)
<class 'numpy.ndarray'>


[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


<ipython-input-20-b7325d40deb6>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_a = np.array(a)


ndarray는 상수와의 연산, ndarray와의 연산, 행렬연산 등 다양한 연산을 지원한다.

In [23]:
b = [[1,2,3],[4,5,6]]
np_b = np.array(b)

c = [[6,5,4],[3,2,1]]
np_c = np.array(c)

print("tensor b")
print(np_b)
print(np_b.shape)

print("\ntensor c")
print(np_c)
print(np_c.shape)

tensor b
[[1 2 3]
 [4 5 6]]
(2, 3)

tensor c
[[6 5 4]
 [3 2 1]]
(2, 3)


In [32]:
print("transpose c")
print(np.transpose(np_c))
print(np_c.T)

transpose c
[[6 3]
 [5 2]
 [4 1]]
[[6 3]
 [5 2]
 [4 1]]


In [33]:
print("reshape c")
print(np_c.reshape((3,2)))
print(np_c.shape)

reshape c
[[6 5]
 [4 3]
 [2 1]]
(2, 3)


In [27]:
print("flatten c")
print(np_c.flatten())

flatten c
[6 5 4 3 2 1]


In [28]:
print("b*2:")
print(np_b*2)

b*2:
[[ 2  4  6]
 [ 8 10 12]]


In [29]:
#element wise add element단위 덧셈
print("b+c:")
print(np_b+np_c)

b+c:
[[7 7 7]
 [7 7 7]]


In [30]:
#element wise product element단위 곱셈
print("b*c:")
print(np_b*np_c)

b*c:
[[ 6 10 12]
 [12 10  6]]


In [31]:
#dot 행렬곱
print("b dot transpose c")
print(np.dot(np_b,np_c.T))

b dot transpose c
[[28 10]
 [73 28]]
